import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Page from "./page";
export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout() {
  const user1 = {
    userName: "Robe Kyle",
    taskNumber: 20
  };

  return (
    <html lang="en">
      <body>
        <Header userName={user1.userName} taskNumber={user1.taskNumber}/>
        <Page/>
      </body>
    </html>
  );
}
