import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Page from "./page";

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Page/>
      </body>
    </html>
  );
}
